version: '1.0'

services:
  linuxenv:
    #image: linuxenv-kde:centos7.9.2009
    #image: linuxenv-gnome:centos7.9.2009
    #image: linuxenv-xfce:centos7.9.2009
    image: linuxenv:centos7.9.2009
    container_name: linuxenv-centos
    hostname: linuxenv
    user: root
    privileged: true
    cap_add:
      #- CAP_NET_ADMIN
      #- CAP_SYS_ADMIN
      - ALL
    ports:
      - '3022:22'
      - '3388:3389'
    command: "/usr/sbin/init"
    shm_size: 512m
    #mem_limit: 16g
    volumes:
      #Maven
      - /d/dev_yore/mvn_repository:/opt/repository
      # code
      - /d/dev_yore:/opt/dev_yore
    extra_hosts:
      - "node01:172.22.80.1"

networks:
  centos_default:
    driver: bridge
