version: '1.0'

services:
  linuxenv:
    #image: linuxenv-gnome:latest
    #image: linuxenv-xfce:latest
    #image: linuxenv-deepin:latest
    #image: linuxenv-lxqt:latest
    image: linuxenv:latest
    container_name: linuxenv-ubuntu
    hostname: linuxenv
    user: root
    privileged: true
    cap_add:
      #- CAP_NET_ADMIN
      #- CAP_SYS_ADMIN
      - ALL
    ports:
      - '3022:22'
      - '3388:3389'
    shm_size: 512m
    volumes:
      #Maven
      - /d/dev_yore/mvn_repository:/opt/repository
      # code
      - /d/dev_yore:/opt/dev_yore
    #extra_hosts:
      #- "node01:172.22.80.1"

networks:
  linuxenv_default:
    driver: bridge
