version: '1.0'

services:
  linuxenv:
    image: linuxenv:latest
    container_name: linuxenv
    hostname: linuxenv
    user: root
    privileged: true
    cap_add:
      #- CAP_NET_ADMIN
      #- CAP_SYS_ADMIN
      - ALL
    ports:
      - '3022:22'
      - '3388:3389'
    #command: '/usr/bin/bash /etc/rc2.d/S02myinit'
    shm_size: 512m
    volumes:
      #- './bin/init.sh:/opt/init.sh'
      #Maven
      - /d/dev_yore/mvn_repository:/opt/repository
      #- '/c/Users/admin/.m2/repository:/home/yore/.m2/repository'
      # code
      #- '/c/Users/admin/Public:/home/yore/Public'
      - /d/dev_yore:/opt/dev_yore
    extra_hosts:
      - "node01:172.22.80.1"
